### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by allanoguis** [allanoguis/Hacktoberfest-2024#1]
The navigation bar is currently empty. UX/UI needed.

**Comment by allanoguis** [comment]
Sure! We can work on in together. You can join my Discord channel so we can coordinate better

**Comment by vaibhav-gosavi** [comment]
hey i can you assign me this issue

**Comment by allanoguis** [comment]
Sure @vaibhav-gosavi. How would you like to design the nav bar?

**Comment by vaibhav-gosavi** [comment]
thinking of adding a high score a help and setting and a toggle button for dark and light mode , also give me you insights for more enhancement

**Comment by allanoguis** [comment]
That's a good idea. We can make a separate page for the highscore although we might go the "login with google account" route with that option. Let's talk about the initial design of the nav-bar. what kind of layout do you have in mind? 

I'm thinking of a nav-bar on top for desktop layout and it goes all the way to the bottom on mobile.

**Comment by vaibhav-gosavi** [comment]
ok nice idea so i will add this below thing in the navbar that is profile, highscore, setting, help.

**Comment by allanoguis** [comment]
Yeah that would be a great idea.

**Comment by vaibhav-gosavi** [comment]
also add Hacktoberfest or Hacktoberfest-accepted tags in you repo

**Comment by vaibhav-gosavi** [comment]
hey earlier i made a PR and you merged it but this is what i am getting 
![image](https://github.com/user-attachments/assets/3d208ac7-6519-470d-95d6-3b37386dd42e)
in my account of hacktoberfest website any idea?

**Comment by vaibhav-gosavi** [comment]
can you add hacktoberfest-accepted label to his issue

**Comment by allanoguis** [comment]
Oh i see. Don't worry I'll update all the issues including the closed ones. Thanks for the info
