### ISSUE TITLE
need UI Changes in the Footer 

### ISSUE THREAD

**Issue by vaibhav-gosavi** [allanoguis/Hacktoberfest-2024#17]
The Footer of the website is Currently empty need UI changes

**Comment by vaibhav-gosavi** [comment]
Hey assign it to me

**Comment by PRAteek-singHWY** [comment]
@allanoguis  Please assign this issue to me , i would love to work on this .

**Comment by allanoguis** [comment]
Hi @PRAteek-singHWY, @vaibhav-gosavi  is already working on this issue. You can check for other issues or create one if you think you can make enhancements to the website. Don't forget to fork, clone and star the repo. 

I personally check all the issues and PR requests to avoid merge conflicts. Check the Readme.md also thanks!

**Comment by vaibhav-gosavi** [comment]
The UI is Fixed

**Comment by allanoguis** [comment]
I'll set a milestone on the project tracker. Thank you @vaibhav-gosavi you've gone hard on the project, I appreciate it
