### ISSUE TITLE
Pixel Art animation for Gojira: Idle

### ISSUE THREAD

**Issue by allanoguis** [allanoguis/Hacktoberfest-2024#19]
Here is a sample pixel art for Gojira. We need to animate this via a set of pixel art and create an animation grid. 

Link: (https://www.pixilart.com/photo/gojirun-f15ba304802ba84)

Bounty:
Idle animation before the game starts

**Comment by vaibhav-gosavi** [comment]
hey let me work on this, i think we need animation.js to work on this where exactlly you want me to work on this which section is that in the web page if you could give me some more details i would work on it

**Comment by allanoguis** [comment]
Hi @vaibhav-gosavi I am currently designing the pixel art for gojira. but it's taking alot of time. For the meantime, I got a sample SNES rip from Bonsai, a sprite sheet to animate the model. we can go to #discussions or go to my discord channel if you are available so we could coordinate better. which do you prefer?
