### ISSUE TITLE
Collaborators section

### ISSUE THREAD

**Issue by allanoguis** [allanoguis/Hacktoberfest-2024#2]
The collaborators section is currentyl empty.

The Collaborators Section would feature the collaborators on this project. 

We can discuss how to implement this.

**Comment by Sauhard74** [comment]
hey can i work on this issue

**Comment by parthib2004** [comment]
Can you please assign these to me?

**Comment by allanoguis** [comment]
Sure, just fork the repo and make PR submissions.

**Comment by vaibhav-gosavi** [comment]
hey let me work on this
