### ISSUE TITLE
the UI for Collaborators Page Need to look good 

### ISSUE THREAD

**Issue by vaibhav-gosavi** [allanoguis/Hacktoberfest-2024#28]
create a nice ui for collaborators page the existing one the idea is good

**Comment by vaibhav-gosavi** [comment]
hey @allanoguis let me work on this i will try to get the actually contributes in project to that page that will be dynamic we don't have to hard code any contributes here.

**Comment by allanoguis** [comment]
You read through my mind! I was just about to create an issue about the collaborators' section. Wait I'll set up the issue.

the collaborators are JSON

![image](https://github.com/user-attachments/assets/4b079a91-a8aa-454e-823b-e0fc50faec5e)

they are just placeholders I just needed to see earlier how it would look like.

**Comment by allanoguis** [comment]
You'll be able to work on this part now I'll work on the engine again. GLHF

**Comment by vaibhav-gosavi** [comment]
well i already made a pull request on this go check on that and there are some conflits resolve it and merge it in the main branch and i tested the site and built it in the local so there wont be any build issues i guess if you want to test do a npm run build in local

**Comment by allanoguis** [comment]
Got it. Checking it now

**Comment by allanoguis** [comment]
Fixed: #30
