### ISSUE TITLE
The Whole websites color Them should match 

### ISSUE THREAD

**Issue by vaibhav-gosavi** [allanoguis/Hacktoberfest-2024#29]
the whole website UI Theme should Match

**Comment by vaibhav-gosavi** [comment]
hey @allanoguis  hey me work on this

**Comment by allanoguis** [comment]
Fire away my dude. Thanks for helping out!

**Comment by allanoguis** [comment]
Also, please check the #27 Announcements. I installed shadcn  for further info.

**Comment by vaibhav-gosavi** [comment]
this is fixed done

**Comment by allanoguis** [comment]
lookin good! Let's work on the game engine now
![image](https://github.com/user-attachments/assets/7631fb51-ab93-4f4b-9b9c-ad059caa3dba)
