### ISSUE TITLE
Add Contributors to ReadME.md

### ISSUE THREAD

**Issue by allanoguis** [allanoguis/Hacktoberfest-2024#42]
Add a list of Contributors to the Readme file dynamically

**Comment by vprathap21** [comment]
I’d like to work on this. Could you please assign the issue to me?

**Comment by allanoguis** [comment]
Sure! GLHF!

**Comment by vprathap21** [comment]
Done! Check out PR #44

**Comment by allanoguis** [comment]
Thank you @vprathap21

**Comment by vprathap21** [comment]
Could you please add the hacktoberfest-accepted label to this PR? Thank you!

**Comment by allanoguis** [comment]
@vprathap21  Done! you can check your hacktoberfest profile if it adds up
