### ISSUE TITLE
We need a storage mechanic for the score

### ISSUE THREAD

**Issue by allanoguis** [allanoguis/Hacktoberfest-2024#48]
Which free database can we use for the project to store the scores in the database?

- Score ID
- Player name

and then sort the scores to make a scoreboard

**Comment by vaibhav-gosavi** [comment]
well we, can go with Firebase Firestore or Supabase for real time update or MongoDB would be a solid option

**Comment by Parth-G27** [comment]
If we use mongoDB, and every time the game gets over me make a POST api call with stores the Score with the playerID, by default every row gets a _id in mongoDB so that can be considered as ScoreID.

**Comment by Parth-G27** [comment]
@allanoguis @vaibhav-gosavi Can I take this issue and move forward ?

**Comment by vaibhav-gosavi** [comment]
well that's a good idea but @allanoguis can help us with this if this game going to a multiplayer in the near future or just a solo player game if solo then we can go with mongoDB or else Firebase would be a good option

**Comment by Parth-G27** [comment]
We can have a collection (table) in MongoDB with 3 columns 
{_id: default
score: int 
playerID : int/emailid
}

SO even when multiple players are playing the score for every games goes into the same table. What do you say.... I think same can be done for FireBase NoSQL also @vaibhav-gosavi

**Comment by allanoguis** [comment]
Hi @vaibhav-gosavi @Parth-G27 we should go with the simpler approach. We can keep the game single-player for now for the sake of the Hacktoberfest event. 

Going the Mongodb or Firebase route would be beneficial for us for a simpler straightforward approach.

**Comment by allanoguis** [comment]
I guess we should move this conversation to Discussions so we can track the conversation and monitor where the project is going yea? I'll make a thread for this one.

**Comment by Parth-G27** [comment]
Yes sure.
