### ISSUE TITLE
SVG asset: safari.js

### ISSUE THREAD

**Issue by allanoguis** [allanoguis/Hacktoberfest-2024#5]
The file safari.js has been created and it contains the following:
- created sky
- clouds
- ground
- rocks
- obstacles (cactii)

but needs to be in separate components

**Comment by codeza-ai** [comment]
@allanoguis I would like to contribute, please assign me this under HacktoberFest.

**Comment by codeza-ai** [comment]
Just a little doubt. Do I need to create a separate branch with my name after forking and then create a pr, or I can just work directly on the main branch?

**Comment by allanoguis** [comment]
Hi @codeza-ai I had a problem with merging the assets. Please help

**Comment by codeza-ai** [comment]
@allanoguis I think it is because the repository of the person whose PR you merged (#25 ) didn't update the forked repository when my PR was accepted. I can't make another PR with the same change in the code, otherwise it would be a spammy PR. You can solve this by editing the current code and making it similar to the state when my PR was merged.

**Comment by allanoguis** [comment]
I see, that makes sense. I think I'll just have to set a reminder on the Readme about merge conflicts. Thanks for the insight @codeza-ai . I'll close this issue since I can easily copy from the commit changes.

**Comment by codeza-ai** [comment]
Thanks alot @allanoguis 🙌

**Comment by allanoguis** [comment]
Just want to make sure that the pull request counts on your end. Did it show up on your profile? @codeza-ai 
I'm worried because the contributors did not show your name on the project summary. I wonder what was wrong

**Comment by codeza-ai** [comment]
The PR has reflected in my acc, but the status is waiting. I'll let you know as I get any updates.
