### ISSUE TITLE
ShadCn Library for Components and Dark Theme Implementation

### ISSUE THREAD

**Issue by SunkaraboinaPraveenKumar** [allanoguis/Hacktoberfest-2024#51]
**Is your feature request related to a problem? Please describe.**
It's Easy to use Shadcn UI Components in nextjs and using next-themes to switch between dark and light mode

**Describe the solution you'd like**
Shadcn and next-themes

**Describe alternatives you've considered**

**Additional context**

**Comment by allanoguis** [comment]
Hi @SunkaraboinaPraveenKumar Thanks for checking the project out! 

We have Shadcn installed in the project.
Ref.: #27 

Please give us further details regarding the solution.

**Comment by SunkaraboinaPraveenKumar** [comment]
I can Integrate Clerk Authentication or if needed Authentication using any database and also create a leader board to store the best scores of each user as a leaderboard

**Comment by Parth-G27** [comment]
@SunkaraboinaPraveenKumar The UI which includes footer, game, hero all is being code with plain TailwindCSS.
If we have to use shadCN, do we have to redo the UI for these components again ?

**Comment by SunkaraboinaPraveenKumar** [comment]
No need ShadCn is component library only

**Comment by Parth-G27** [comment]
But the game & the gameEngine are in TailwindCSS, the theme switch of ShadCN wont work on them right ? @SunkaraboinaPraveenKumar . How do we solve that

**Comment by SunkaraboinaPraveenKumar** [comment]
Yes it will not affect any styling we just need to install shadcn and use inbuilt components wherever required like buttons, alert boxes, toasts etc.. instead of hard coding everything. Please do assign me as a part of hacktoberfest 2024 i can do that

**Comment by allanoguis** [comment]
Alright dude have a go at it. We'll check the pull request once you finish it. GLHF!

**Comment by SunkaraboinaPraveenKumar** [comment]
Bro Why is my PR rejected by hacktoberfest saying your repo is registered under hacktober 
![image](https://github.com/user-attachments/assets/a90093b6-0036-4357-a39a-ca4b2b7a55e3)

**Comment by Parth-G27** [comment]
your PR is there which you made 5 hrs ago, @allanoguis will review your PR. Good work @SunkaraboinaPraveenKumar

**Comment by allanoguis** [comment]
Hi @SunkaraboinaPraveenKumar I'm still checking the PR. Once merge then I'll put the tags on it. I reviewed your PR and here's what I found:

![image](https://github.com/user-attachments/assets/04a658e5-6163-4c80-b531-8aa416365156)

The Navigation bar was not used on the page. 

![image](https://github.com/user-attachments/assets/9fb40250-8f8e-485e-9aab-80d4a5fe7bba)

Can I have more information about this PR? I might also suggest a few fixes before having it approved.  I appreciate the effort made in this development

**Comment by SunkaraboinaPraveenKumar** [comment]
Bro Please convert .env.example to .env.local which has clerk api keys then you can as git will not allow .env.local i adjusted it

**Comment by SunkaraboinaPraveenKumar** [comment]
Once it is deployed no need of such keys but for local machine needed

**Comment by allanoguis** [comment]
@SunkaraboinaPraveenKumar still having the same error dude I wonder what's wrong. May I ask for a revisal on the PR request so that we can see the output?
