### ISSUE TITLE
Toggle Dark mode 

### ISSUE THREAD

**Issue by Sarthakkashyapp** [allanoguis/Hacktoberfest-2024#69]
This is a feature request to implement a toggles dark mode into the website so that it make it more appealing and also becomes easier to use this at night. 
@allanoguis I would like to work on this issue.
Assign this to me under gssoc-ext and hacktoberfest-accepted labels

**Comment by allanoguis** [comment]
Hi @Sarthakkashyapp we already have dark mode enabled on the site. please check your forked repo to make sure that it is the updated version of the project. Cheers!
