### ISSUE TITLE
Card Component design for the highscore page

### ISSUE THREAD

**Issue by allanoguis** [allanoguis/Hacktoberfest-2024#73]
![image](https://github.com/user-attachments/assets/fe5c63da-82c2-4964-a0db-5368718cd15d)

The cards should be designed to show player score records for the leaderboard modal

**Comment by BimleshRB** [comment]
I can't understand what you actually wanted to be implemented

**Comment by allanoguis** [comment]
Hi @BimleshRB This one is done already.
