### ISSUE TITLE
 Footer Alignment Issue: Misaligned Copyright Text

### ISSUE THREAD

**Issue by ansiace** [allanoguis/Hacktoberfest-2024#78]
Bug: Copyright Text Not Properly Aligned in Footer
The copyright text in the footer section is not placed correctly, which impacts the overall look and feel of the page. The text appears off-center, making the footer visually unbalanced.

Expected Behavior:

The copyright text should be centered horizontally within the footer for a cleaner, more balanced layout.

Proposed Solution:
Adjust the alignment of the copyright text to center it within the footer section.

![Screenshot 2024-10-13 032846(1)(1)](https://github.com/user-attachments/assets/795ab03f-8f23-4d39-a7b9-e3bc7d389053)

**Comment by allanoguis** [comment]
Go ahead @ansiace Don't forget to update your fork and leave a star on this project! Thanks!

**Comment by allanoguis** [comment]
hey @ansiace you good bro?

**Comment by ansiace** [comment]
I am not getting the key.json file which is used in server/firebadeConfig.js 

Could you please help me with how to obtain or generate this key.json file for Firebase?

**Comment by allanoguis** [comment]
@ansiace what would you need the key.json for? the issue is footer alignment you have posted.

**Comment by ansiace** [comment]
Thank you for your comment! I needed the key.json because the app was not running on my end, so I couldn’t check the issue properly without it. Once I have it, I’ll be able to proceed with fixing the footer alignment as well.

**Comment by allanoguis** [comment]
@ansiace you can actually propose a design of your own with you choice of content which ever would make the footer enhancement. doesn't have to be the "subscribe to email button".  as long as it adds value to the following:
- exposure of the project
- readability (in terms or website content/extra info that is not redundant)
- UX/UI

**Comment by ansiace** [comment]
@allanoguis I can't change anything till I get the key.json file it is required to run the app. Your app is not running properly it shows an error regarding key.json file.

**Comment by ansiace** [comment]
Since the app is not running properly due to the missing key.json file, I’m unable to proceed with any changes. I will be closing this issue for now.
