### ISSUE TITLE
UPDATION IN README.md FILE REQUIRED 

### ISSUE THREAD

**Issue by soham0028** [allanoguis/Hacktoberfest-2024#79]
Hello @allanoguis 
The current readme file does not contain :
1. proper structure 
2. table of content 
3. contributers section 
4. forkers and stargazers section 
5. back to top button 

Kindly assign me the issues under hacktoberfest labels so my work counts

**Comment by allanoguis** [comment]
@soham0028 Go ahead, you can start on this issue now. GLHF!

**Comment by soham0028** [comment]
Thankyou will revert back asap
