### ISSUE TITLE
hacktoberfest2024

### ISSUE THREAD

**Issue by Sumits-Cosmos** [allanoguis/Hacktoberfest-2024#88]
hey @allanoguis, i would like to contribute to this project.
Could you assign me the project?
Kindly suggest the areas where i can work.

**Comment by allanoguis** [comment]
Hi @Sumits-Cosmos, what areas are you interested in? back end/front end/game development?
So we can discuss this further.

**Comment by Sumits-Cosmos** [comment]
frontend and Backend @allanoguis.

**Comment by allanoguis** [comment]
We can talk about this on Discord if you want @Sumits-Cosmos so we can be sure we are on the same page. What do you say?

**Comment by Sumits-Cosmos** [comment]
@allanoguis yes, we can. 
If you can mention your discord id.

**Comment by allanoguis** [comment]
@Sumits-Cosmos 299087513501302786
