### ISSUE TITLE
alignment and spacing of nav bar

### ISSUE THREAD

**Issue by irshadsiddi** [allanoguis/Hacktoberfest-2024#89]
hey, @allanoguis 

![image](https://github.com/user-attachments/assets/aaf9d827-64b0-4cde-b521-27f57b51923e)
here in the navbar the spacing is not good.. 

i would like to work on this.. please assign this to me

**Comment by allanoguis** [comment]
Hi @irshadsiddi, we are doing a major refactor on the front and back end of the page. I might close this issue because the scope affects the page layout. Thanks!
